# Generated by Django 4.2.2 on 2023-09-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_item_alter_order_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='repository',
            field=models.ForeignKey(db_column='repository_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.repository'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(db_column='orderer_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='repository',
            field=models.ForeignKey(db_column='repository_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.repository'),
        ),
    ]
